sudo: false
dist: trusty
language: rust
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - rust: stable


addons:
  apt:
    packages:
      - openssl
      - libcurl4-openssl-dev

cache: cargo

before_script:
  # Install tools if not already installed
  - cargo install --list | grep clippy || cargo install clippy
  - cargo install --list | grep rustfmt || cargo install rustfmt
  # Update all tools
  - cargo install --list | grep cargo-update || cargo install cargo-update || true # sometimes nightly breaks stuff, that's okay
  - cargo install-update -a
  
  # Lint
  - cargo fmt -- --write-mode=diff
  - cargo clippy -- -Z no-trans -D clippy -D warnings
